<?php use gtf\Router; ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf8" />
	<title>Done</title>
	<link rel="stylesheet" type="text/css" href="<?=Router::res('css/bootstrap.css')?>" />
	<link rel="stylesheet" type="text/css" href="<?=Router::res('css/info.css')?>" />
</head>
<body class="container">
	<div class="page-header">
		<h1>Done! <div class="pull-right">^_^</div></h1>
	</div>
	<div class="content">
		<p class="well">
			<?=$var['message']?>
		</p>
		<div class="more">
			<?php if (isset($var['link'])): ?>
				<a class="btn btn-primary" href="<?=$var['link']?>">Back</a>
			<?php else: ?>
				<a class="btn disabled">Back</a>
			<?php endif; ?>
		</div>
	</div>
</body>
</html>