<!DOCTYPE html>
<html>
<head>
  <meta charset="utf8" /><?php use Gtf\Router; ?>
  <title>Dorm log - Powered by Gtf</title>
  <link rel="stylesheet" href="<?=Router::res('css/bootstrap.css')?>" />
  <link rel="stylesheet" href="<?=Router::res('css/grid.css')?>" />
  <link rel="stylesheet" href="<?=Router::res('css/task.css')?>" />
  <script type="text/javascript" src="<?=Router::res('js/jquery.min.js')?>"></script>
</head>
<body class="container">
  <div class="topbar">
    <span class="name">Current user: <?=$_SESSION['name']?></span>
    <span class="login pull-right"><a href="<?=Router::site('index.php/logout')?>">Logout</a></span>
  </div>
  <div class="row-fluid">
    <div class="span9">
      <h1>Dorm log </h1>
      <ul class="nav nav-tabs">
        <li<?=$var['all']?' class="active"':''?>>
          <a href="<?=Router::site("index.php")?>">All</a>
        </li>
        <?php foreach ($var['years'] as $key=>$value): ?>
        <li<?=$value?' class="active"':''?>><a href="<?=Router::site("index.php/year/$key")?>"><?=$key?></a></li>
        <?php endforeach; ?>
        <li>
          <li><a href="#addlog" data-toggle="tab"><i class="icon-black icon-plus"></i></a></li>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="log-list">
          <table class="table table-hover">
            <thead>
              <tr>
                <th width="30%">Date</th>
                <th width="50%">Detail</th>
                <th width="20%">Amount</th>
              </tr>
            </thead>
            <tbody>
              <?php if ($var['log']): ?>
              <?php foreach ($var['log'] as $item): ?>
                <tr>
                  <td><?=$item['date']?></td>
                  <td><?=$item['detail']?></td>
                  <td class="number"><?=$item['amount']?></td>
                </tr>
              <?php endforeach; ?>
              <?php else: ?>
                <tr class="info no-record"><td colspan="3">No record yet~</td></tr>
              <?php endif; ?>
            </tbody>
              <tr>
                <td colspan="2">Sum of amount:</td>
                <td class="number"><?=$var['sum']?$var['sum']:0?></td>
              </tr>
            <tfoot>
            </tfoot>
          </table>
          <div class="pagination pagination-mini pagination-centered">
            <ul>
              <li<?=$var['prev_page']>1?'':' class="disabled"'?>>
                <a href="<?=$_SERVER['PHP_SELF']."?page={$var[prev_page]}"?>">«</a>
              </li>
              <?php for($i=1; $i<$var['current_page']; $i++): ?>
              <li><a href="<?=$_SERVER['PHP_SELF']."?page=$i"?>"><?=$i?></a></li>
              <?php endfor; ?>
              <li class="active"><a href="<?=$_SERVER['PHP_SELF']."?page=$i"?>"><?=$i?></a></li>
              <?php for(; $i<$var['pages']; $i++): ?>
              <li><a href="<?=$_SERVER['PHP_SELF']."?page=$i"?>"><?=$i?></a></li>
              <?php endfor; ?>
              <li<?=$var['next_page']<$var['pages']?'':' class="disabled"'?>>
                <a href="<?=$_SERVER['PHP_SELF']."?page=$var[next_page]"?>">»</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="tab-pane" id="addlog">
          <?php if (isset($_SESSION['role']) && $_SESSION['role'] == 1): ?>
          <form action="<?=Router::site("index.php/addLog")?>" method="POST" class="form-horizontal">
            <fieldset>
              <legend>Add a record</legend>
              <div class="control-group">
                <label class="control-label" for="date">Date</label>
                <div class="controls">
                  <input type="date" id="date" name="date" value="<?=(new DateTime())->format('Y-m-d')?>" placeholder="Date" />
                </div>
              </div>
              <div class="control-group">
                <label class="control-label" for="detail">Detail</label>
                <div class="controls">
                  <textarea id="detail" name="detail" placeholder="Detail of the balance"></textarea>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label" for="amount">Balance</label>
                <div class="controls">
                  <input type="number" id="amount" name="amount" placeholder="Amount" />
                </div>
              </div>
              <div class="form-actions">
                <button class="btn btn-primary" type="submit">Submit</button>
                <button class="btn" type="reset">Reset</button>
              </div>
            </fieldset>
          </form>
          <?php endif; ?>
        </div>
      </div>
      
    </div>
    <div class="span3">
      <?=comp\CalendarTable::instance(array(
            "table_class" => "",
            "today"       => Router::site("index.php/date/%Y-%m-%d"),
            "day"         => Router::site("index.php/date/%Y-%m-%d")
      ))?>
    </div>
  </div>
  <script type="text/javascript" src="<?=Router::res('js/bootstrap.js')?>"></script>
  <script type="text/javascript" src="<?=Router::res('js/jquery.editor.js')?>"></script>
  <script type="text/javascript" src="<?=Router::res('js/index.js')?>"></script>
</body>
</html>
