<?php $this->ext('view/base.phtml'); use gtf\Router; ?>

<?php $this->block('body') ?>
<form action="<?=Router::site('user.php')?>" method="POST" class="form-horizontal">
  <fieldset>
    <legend>Passcode for Administration</legend>
    <?php if (!file_exists('core/admin.config.php')): ?>
    <div class="alert alert-info">
      <p><strong>Warning!</strong>It seems that this is the first time to use the system. We need a passcode to access the administration work.</p>
    </div>
    <?php else: ?>
    <div class="alert alert-info">
      <p><strong>INFO: </strong> Normally management page is <a href="<?=Router::site('index.php')?>">here</a>.</p>
    </div>
    <?php endif; ?>

    <div class="control-group">
      <label class="control-label" for="username">Passcode:</label>
      <div class="controls">
        <input type="text" name="code" placeholder="Pass code" />
      </div>
    </div>

    <div class="form-actions">
      <button class="btn btn-primary" type="submit">Submit</button>
      <button class="btn" type="reset">Reset</button>
    </div>
	</fieldset>
</form>
<?php $this->end() ?>